mutag_calibration:
  taggers:
    - globalParT3_XbbVsQCD
  pt_binning:
    "2024":
      - [250, 'Inf']
      - [250, 350]
      - [350, 'Inf']
  msd_binning:
    "2024":
      - [100, 150]
      - [50, 200]
  wp:
    "2024":
      globalParT3_XbbVsQCD:
        HHbbbb_WP_MP: 0.95
        HHbbbb_WP_HP: 0.975
        HHbbbb_WP_VHP: 0.99
        HHbbbb_HP: "0.975-0.99"
        HHbbbb_MP: "0.95-0.975"
